import "./globals.css";
import Link from "next/link";
import { AppBar } from "@/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }:any) {
  return (
    <html lang="en"><body className="flex">
        <AppBar />
        {children}
      </body></html>
      
    
  );
}
