import "./globals.css";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }:any) {
  return (
    <html lang="en"><body>
        <div>
          <Link href="/votes">Votes</Link>
          <Link href="/breeds">Breeds</Link>
          <Link href="/gallery">Gallery</Link>
        </div>
        {children}
      </body></html>
      
    
  );
}
